"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowDownToLine, ArrowUpFromLine, Download, FileText, History, Loader2, Plus, RefreshCw, Search, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useToast } from "@/components/ui/toast";

type Product = { id: string; name: string; type: "FERTILIZER" | "PESTICIDE"; stock: number; unit: string; status: string; imageUrls: string[] };
type Movement = { id: string; productId: string; quantity: number; stockBefore: number; stockAfter: number; product: { name: string; unit: string } };
type Document = { id: string; code: string; type: "PN" | "PX" | "DC" | "HT"; businessType: string; supplierName?: string | null; actorName?: string | null; createdAt: string; order?: { id: string; orderCode: string } | null; movements: Movement[] };
type FormItem = { productId: string; quantity: string; note: string };

const businessLabels: Record<string, string> = {
    SUPPLIER_IMPORT: "Nhập từ nhà cung cấp", STOCK_REPLENISHMENT: "Nhập bổ sung tồn", RETURNED_GOODS_IMPORT: "Nhập hàng trả về",
    DISPOSAL_EXPORT: "Xuất hủy", TRANSFER_EXPORT: "Xuất điều chuyển", STOCKTAKE_INCREASE: "Kiểm kê tăng", STOCKTAKE_DECREASE: "Kiểm kê giảm",
    CUSTOMER_RETURN: "Khách trả hàng", SUPPLIER_RETURN: "Trả nhà cung cấp", SALE_EXPORT: "Xuất bán hàng", OPENING_BALANCE: "Số dư đầu kỳ",
};

export function InventoryManager() {
    const { toast } = useToast();
    const [products, setProducts] = useState<Product[]>([]); const [documents, setDocuments] = useState<Document[]>([]); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [selectedProduct, setSelectedProduct] = useState("ALL"); const [businessType, setBusinessType] = useState("SUPPLIER_IMPORT");
    const [createdDate, setCreatedDate] = useState(() => new Date().toLocaleDateString("en-CA"));
    const [items, setItems] = useState<FormItem[]>([{ productId: "", quantity: "", note: "" }]);
    const [activeTab, setActiveTab] = useState<"stock" | "create" | "history">("stock");
    const [search, setSearch] = useState(""); const [productType, setProductType] = useState("ALL"); const [stockStatus, setStockStatus] = useState("ALL");
    const [historyFrom, setHistoryFrom] = useState(""); const [historyTo, setHistoryTo] = useState(""); const [historyBusiness, setHistoryBusiness] = useState("ALL"); const [documentSearch, setDocumentSearch] = useState("");
    const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/store/inventory", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message); setProducts(payload.products || []); setDocuments(payload.documents || []); } catch (error) { toast({ title: "Không thể tải kho hàng", description: error instanceof Error ? error.message : "Vui lòng thử lại.", variant: "destructive" }); } finally { setLoading(false); } }, [toast]);
    useEffect(() => { void load(); }, [load]);
    useEffect(() => { const params = new URLSearchParams(window.location.search); if (params.get("tab") === "create") setActiveTab("create"); const productId = params.get("productId"); if (productId) setItems([{ productId, quantity: "", note: "" }]); }, []);
    const visibleProducts = useMemo(() => products.filter((product) => product.name.toLocaleLowerCase("vi").includes(search.trim().toLocaleLowerCase("vi")) && (productType === "ALL" || product.type === productType) && (stockStatus === "ALL" || (stockStatus === "LOW" ? product.stock <= 5 : stockStatus === "OUT" ? product.stock === 0 : product.stock > 5))), [products, search, productType, stockStatus]);
    const visibleDocuments = useMemo(() => documents.filter((document) => (selectedProduct === "ALL" || document.movements.some((movement) => movement.productId === selectedProduct)) && (historyBusiness === "ALL" || document.businessType === historyBusiness) && (!documentSearch.trim() || document.code.toLocaleLowerCase("vi").includes(documentSearch.trim().toLocaleLowerCase("vi"))) && (!historyFrom || document.createdAt.slice(0, 10) >= historyFrom) && (!historyTo || document.createdAt.slice(0, 10) <= historyTo)), [documents, selectedProduct, historyBusiness, documentSearch, historyFrom, historyTo]);
    const totalStock = products.reduce((sum, product) => sum + product.stock, 0); const lowStock = products.filter((product) => product.stock <= 5).length;
    const today = new Date().toLocaleDateString("en-CA"); const todayDocuments = documents.filter((document) => new Date(document.createdAt).toLocaleDateString("en-CA") === today).length;
    const needsSupplier = ["SUPPLIER_IMPORT", "SUPPLIER_RETURN"].includes(businessType);
    const needsOrder = ["CUSTOMER_RETURN", "SALE_EXPORT"].includes(businessType);
    const needsReason = ["SUPPLIER_RETURN", "DISPOSAL_EXPORT"].includes(businessType);

    async function submit(event: React.FormEvent<HTMLFormElement>) {
        event.preventDefault(); setSubmitting(true); const form = event.currentTarget; const data = new FormData(form);
        try {
            const response = await fetch("/api/store/inventory", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ createdDate, businessType, items: items.map((item) => ({ ...item, quantity: Number(item.quantity) })), supplierName: data.get("supplierName"), orderCode: data.get("orderCode"), reason: data.get("reason"), note: data.get("note") }) });
            const payload = await response.json(); if (!response.ok) throw new Error(payload.message);
            toast({ title: `Đã tạo ${payload.document.code}`, description: "Tồn kho và chứng từ truy vết đã được cập nhật.", variant: "success" }); form.reset(); setBusinessType("SUPPLIER_IMPORT"); setCreatedDate(new Date().toLocaleDateString("en-CA")); setItems([{ productId: "", quantity: "", note: "" }]); await load();
        } catch (error) { toast({ title: "Không thể tạo chứng từ", description: error instanceof Error ? error.message : "Vui lòng thử lại.", variant: "destructive" }); } finally { setSubmitting(false); }
    }

    function exportInventory() {
        const rows = [["STT", "Sản phẩm", "Loại", "Đơn vị", "Tồn hiện tại"], ...visibleProducts.map((product, index) => [String(index + 1), product.name, product.type === "FERTILIZER" ? "Phân bón" : "Thuốc BVTV", product.unit, String(product.stock)])];
        const csv = rows.map((row) => row.map((cell) => `"${cell.replace(/"/g, '""')}"`).join(",")).join("\r\n"); const url = URL.createObjectURL(new Blob(["\ufeff", csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `ton-kho-${today}.csv`; anchor.click(); URL.revokeObjectURL(url);
    }

    return <div className="space-y-6">
        <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Sản phẩm" value={products.length} /><Stat label="Tổng đơn vị" value={totalStock} /><Stat label="Sắp hết" value={lowStock} warning={lowStock > 0} /><Stat label="Chứng từ hôm nay" value={todayDocuments} /></section>
        <section className="flex flex-col gap-3 rounded-3xl border bg-white p-4 shadow-sm lg:flex-row lg:items-center">
            <div className="relative min-w-0 flex-1"><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-400" /><Input value={activeTab === "history" ? documentSearch : search} onChange={(event) => activeTab === "history" ? setDocumentSearch(event.target.value) : setSearch(event.target.value)} className="pl-10" placeholder={activeTab === "history" ? "Tìm mã chứng từ..." : "Tìm sản phẩm..."} /></div>
            <Button variant="outline" onClick={() => { setSearch(""); setProductType("ALL"); setStockStatus("ALL"); setHistoryFrom(""); setHistoryTo(""); setHistoryBusiness("ALL"); setSelectedProduct("ALL"); setDocumentSearch(""); void load(); }}><RefreshCw className="mr-2 h-4 w-4" />Làm mới</Button>
            <Button onClick={() => setActiveTab("create")}><Plus className="mr-2 h-4 w-4" />Tạo chứng từ mới</Button>
        </section>
        <nav className="flex overflow-x-auto border-b border-slate-200" aria-label="Quản lý kho">{([['stock', 'Tồn kho hiện tại'], ['create', 'Tạo chứng từ'], ['history', 'Lịch sử kho']] as const).map(([value, label]) => <button key={value} type="button" onClick={() => setActiveTab(value)} className={`whitespace-nowrap border-b-2 px-5 py-3 text-sm font-bold transition-colors ${activeTab === value ? "border-emerald-600 text-emerald-700" : "border-transparent text-slate-500 hover:text-slate-900"}`}>{label}</button>)}</nav>

        {activeTab === "stock" && <section className="overflow-hidden rounded-3xl border bg-white shadow-sm">
            <header className="space-y-4 border-b p-5"><h2 className="text-xl font-bold">Tồn kho hiện tại</h2><div className="flex flex-col gap-3 lg:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input value={search} onChange={(event) => setSearch(event.target.value)} className="h-10 pl-10" placeholder="Tìm theo tên sản phẩm..." /></div><select value={productType} onChange={(event) => setProductType(event.target.value)} className="h-10 rounded-xl border bg-white px-3 text-sm"><option value="ALL">Tất cả loại vật tư</option><option value="FERTILIZER">Phân bón</option><option value="PESTICIDE">Thuốc BVTV</option></select><select value={stockStatus} onChange={(event) => setStockStatus(event.target.value)} className="h-10 rounded-xl border bg-white px-3 text-sm"><option value="ALL">Tất cả trạng thái tồn</option><option value="AVAILABLE">Còn hàng</option><option value="LOW">Sắp hết (≤ 5)</option><option value="OUT">Hết hàng</option></select><Button size="sm" variant="outline" onClick={exportInventory}><Download className="mr-2 h-4 w-4" />Xuất Excel</Button></div></header>
            {loading ? <div className="flex justify-center py-16"><Loader2 className="h-8 w-8 animate-spin" /></div> : <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="w-20 p-4 text-center">STT</th><th className="p-4">Sản phẩm</th><th className="p-4">Loại</th><th className="p-4">Đơn vị</th><th className="p-4 text-right">Tồn hiện tại</th></tr></thead><tbody className="divide-y">{visibleProducts.map((product, index) => <tr key={product.id} className="hover:bg-slate-50"><td className="p-4 text-center">{index + 1}</td><td className="p-4 font-bold">{product.name}</td><td className="p-4">{product.type === "FERTILIZER" ? "Phân bón" : "Thuốc BVTV"}</td><td className="p-4">{product.unit}</td><td className={`p-4 text-right text-lg font-black ${product.stock === 0 ? "text-red-600" : product.stock <= 5 ? "text-amber-600" : "text-emerald-700"}`}>{product.stock}</td></tr>)}{!visibleProducts.length && <tr><td colSpan={5} className="p-12 text-center text-slate-500">Không tìm thấy sản phẩm phù hợp.</td></tr>}</tbody></table></div>}
        </section>}

        {activeTab === "create" && <form onSubmit={submit} className="space-y-5 rounded-3xl border bg-white p-5 shadow-sm sm:p-6">
            <div><h2 className="flex items-center gap-2 text-xl font-bold"><FileText className="h-5 w-5 text-emerald-600" />Tạo chứng từ kho</h2><p className="mt-1 text-sm text-slate-500">Mã PN/PX được hệ thống cấp tự động.</p></div>
            <div className="grid gap-4 md:grid-cols-2"><label className="block text-sm font-semibold">Ngày tạo<Input type="date" required value={createdDate} onChange={(event) => setCreatedDate(event.target.value)} className="mt-1" /></label><label className="block text-sm font-semibold">Loại nghiệp vụ<select name="businessType" value={businessType} onChange={(event) => setBusinessType(event.target.value)} className="mt-1 h-12 w-full rounded-2xl border border-slate-200 bg-white px-3"><optgroup label="Nhập kho"><option value="SUPPLIER_IMPORT">Nhập từ nhà cung cấp</option><option value="CUSTOMER_RETURN">Khách trả hàng</option></optgroup><optgroup label="Xuất kho"><option value="SALE_EXPORT">Xuất bán hàng</option><option value="SUPPLIER_RETURN">Trả nhà cung cấp</option><option value="DISPOSAL_EXPORT">Xuất hủy</option></optgroup></select></label></div>
            {needsSupplier && <label className="block text-sm font-semibold">Tên nhà cung cấp <span className="text-red-600">*</span><Input name="supplierName" required className="mt-1" placeholder="Ví dụ: Công ty Phân bón Bình Điền" /></label>}
            {needsOrder && <label className="block text-sm font-semibold">Đơn hàng liên quan <span className="text-red-600">*</span><Input name="orderCode" required className="mt-1" placeholder="Ví dụ: DH-20260810-015" /></label>}
            {needsReason && <label className="block text-sm font-semibold">{businessType === "DISPOSAL_EXPORT" ? "Lý do hủy" : "Lý do trả hàng"} <span className="text-red-600">*</span><Input name="reason" required className="mt-1" placeholder={businessType === "DISPOSAL_EXPORT" ? "Ví dụ: Hết hạn sử dụng" : "Ví dụ: Hàng lỗi, cận date, sai quy cách"} /></label>}
            <label className="block text-sm font-semibold">Ghi chú chung<Input name="note" maxLength={1000} className="mt-1" placeholder="Ghi chú chung cho chứng từ (nếu có)" /></label>
            <div className="overflow-x-auto rounded-2xl border"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="w-16 p-3 text-center">STT</th><th className="p-3">Sản phẩm</th><th className="w-32 p-3">Đơn vị</th><th className="w-40 p-3">Số lượng</th><th className="p-3">Ghi chú</th><th className="w-16 p-3" /></tr></thead><tbody className="divide-y">{items.map((item, index) => { const product = products.find((candidate) => candidate.id === item.productId); return <tr key={index}><td className="p-3 text-center font-semibold">{index + 1}</td><td className="p-3"><select required value={item.productId} onChange={(event) => setItems((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, productId: event.target.value } : row))} className="h-11 w-full rounded-xl border border-slate-200 bg-white px-3"><option value="">Chọn sản phẩm</option>{products.map((option) => <option key={option.id} value={option.id} disabled={items.some((row, rowIndex) => rowIndex !== index && row.productId === option.id)}>{option.name}</option>)}</select></td><td className="p-3 font-semibold text-slate-600">{product?.unit || "—"}</td><td className="p-3"><Input type="number" min="1" required value={item.quantity} onChange={(event) => setItems((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, quantity: event.target.value } : row))} /></td><td className="p-3"><Input maxLength={500} value={item.note} onChange={(event) => setItems((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, note: event.target.value } : row))} placeholder="Ghi chú (nếu có)" /></td><td className="p-3"><Button type="button" variant="ghost" size="sm" disabled={items.length === 1} onClick={() => setItems((current) => current.filter((_, rowIndex) => rowIndex !== index))} aria-label="Xóa dòng"><Trash2 className="h-4 w-4 text-red-600" /></Button></td></tr>; })}</tbody></table></div>
            <div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><Button type="button" variant="outline" disabled={items.length >= 50} onClick={() => setItems((current) => [...current, { productId: "", quantity: "", note: "" }])}><Plus className="mr-2 h-4 w-4" />Thêm dòng</Button><Button type="submit" className="sm:min-w-48" disabled={submitting || !products.length}>{submitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Lưu chứng từ</Button></div>
        </form>}

        {activeTab === "history" && <section className="rounded-3xl border bg-white shadow-sm">
            <header className="flex flex-col gap-3 border-b p-5 sm:flex-row sm:items-center sm:justify-between">
                <div><h2 className="flex items-center gap-2 text-xl font-bold"><History className="h-5 w-5" />Lịch sử xuất nhập kho</h2><p className="mt-1 text-sm text-slate-500">Theo dõi toàn bộ biến động và bấm mã chứng từ để xem chi tiết.</p></div>
            </header>
            <div className="grid gap-3 border-b p-4 sm:grid-cols-2 xl:grid-cols-5"><Input type="date" value={historyFrom} onChange={(event) => setHistoryFrom(event.target.value)} aria-label="Từ ngày" /><Input type="date" value={historyTo} onChange={(event) => setHistoryTo(event.target.value)} aria-label="Đến ngày" /><select value={historyBusiness} onChange={(event) => setHistoryBusiness(event.target.value)} className="h-12 rounded-2xl border bg-white px-3 text-sm"><option value="ALL">Tất cả nghiệp vụ</option>{Object.entries(businessLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={selectedProduct} onChange={(event) => setSelectedProduct(event.target.value)} className="h-12 rounded-2xl border bg-white px-3 text-sm"><option value="ALL">Tất cả sản phẩm</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select><Input value={documentSearch} onChange={(event) => setDocumentSearch(event.target.value)} placeholder="Tìm chứng từ..." /></div>
            <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm">
                <thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">Thời gian</th><th className="p-4">Sản phẩm</th><th className="p-4">Nghiệp vụ</th><th className="p-4">Số lượng</th><th className="p-4">Tồn trước → sau</th><th className="p-4">Chứng từ</th></tr></thead>
                <tbody className="divide-y">{visibleDocuments.flatMap((document) => document.movements.map((movement) => {
                    const delta = movement.stockAfter - movement.stockBefore; const incoming = delta >= 0;
                    return <tr key={movement.id}><td className="whitespace-nowrap p-4">{new Date(document.createdAt).toLocaleString("vi-VN")}</td><td className="p-4 font-semibold">{movement.product.name}</td><td className="p-4"><span className={`inline-flex items-center rounded-full px-2.5 py-1 text-xs font-bold ${incoming ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"}`}>{incoming ? <ArrowDownToLine className="mr-1 h-3.5 w-3.5" /> : <ArrowUpFromLine className="mr-1 h-3.5 w-3.5" />}{businessLabels[document.businessType] || document.businessType}</span></td><td className="p-4 font-bold">{incoming ? "+" : "−"}{movement.quantity} {movement.product.unit}</td><td className="p-4">{movement.stockBefore} → <b>{movement.stockAfter}</b></td><td className="p-4"><Link href={`/dashboard/store/inventory/${encodeURIComponent(document.code)}`} className="font-black text-emerald-700 underline-offset-4 hover:underline">{document.code}</Link></td></tr>;
                }))}{!visibleDocuments.length && <tr><td colSpan={6} className="p-12 text-center text-slate-500">Chưa có giao dịch kho.</td></tr>}</tbody>
            </table></div>
        </section>}
    </div>;
}

function Stat({ label, value, warning }: { label: string; value: number; warning?: boolean }) { return <div className={`rounded-2xl border p-4 ${warning ? "border-red-200 bg-red-50" : "bg-white"}`}><p className="text-sm text-slate-500">{label}</p><p className={`mt-1 text-3xl font-black ${warning ? "text-red-700" : "text-slate-900"}`}>{value}</p></div>; }
