"use client";
import { FormEvent, useState } from "react";
import { Factory, PackageCheck } from "lucide-react";
import { Button } from "@/components/ui/button";

type RawLot = { id: string; code: string; source: string; farmName: string; currentWeight: number };
export function SimpleProductionManager({ rawLots }: { rawLots: RawLot[] }) {
    const [lots, setLots] = useState(rawLots); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
    async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const rawMaterialLotId = String(form.get("rawMaterialLotId")); const inputWeight = Number(form.get("inputWeight")); setBusy(true); setMessage(""); try { const response = await fetch("/api/processing/production", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form.entries())) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || "Không thể tạo thành phẩm."); setLots((current) => current.map((lot) => lot.id === rawMaterialLotId ? { ...lot, currentWeight: Math.max(0, lot.currentWeight - inputWeight) } : lot).filter((lot) => lot.currentWeight > 0)); setMessage(`${result.message} Mã lô: ${result.data.finishedLot.lotCode}`); event.currentTarget.reset(); } catch (error) { setMessage(error instanceof Error ? error.message : "Có lỗi xảy ra."); } finally { setBusy(false); } }
    return <div className="space-y-5"><header><p className="text-sm font-bold uppercase tracking-wide text-emerald-700">Chế biến – Đóng gói</p><h1 className="mt-1 text-3xl font-black">Bốc múi / Chế biến</h1><p className="mt-2 text-slate-500">Chỉ ghi nhận đầu vào và lô thành phẩm đầu ra; không quản lý chi tiết từng động tác trong xưởng.</p></header>{message && <p className="rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{message}</p>}<form onSubmit={submit} className="space-y-4 rounded-3xl border bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-2"><Label text="Lô chuyển chế biến"><select required name="rawMaterialLotId" className="h-11 w-full rounded-xl border px-3"><option value="">Chọn lô nguyên liệu</option>{lots.map((lot) => <option key={lot.id} value={lot.id}>{lot.code} · {lot.farmName} · còn {lot.currentWeight} kg</option>)}</select></Label><Label text="Phương pháp"><select name="method" className="h-11 w-full rounded-xl border px-3"><option>Bốc múi / Tách múi</option><option>Đông lạnh</option><option>Chế biến tiếp</option></select></Label><Input name="inputWeight" label="Khối lượng đầu vào (kg)" /><Input name="outputWeight" label="Khối lượng thành phẩm (kg)" /><Input name="productName" label="Tên sản phẩm" text defaultValue="Múi sầu riêng đông lạnh" /><Input name="packaging" label="Quy cách đóng gói" text defaultValue="Đóng túi/thùng" /></div><Label text="Ghi chú"><textarea name="note" className="min-h-20 w-full rounded-xl border p-3" /></Label><Button disabled={busy || !lots.length} className="h-11 bg-emerald-600 hover:bg-emerald-700"><PackageCheck className="mr-2 h-4 w-4" />{busy ? "Đang tạo..." : "Tạo lô thành phẩm"}</Button></form>{!lots.length && <div className="rounded-3xl border border-dashed bg-white p-10 text-center text-slate-500"><Factory className="mx-auto mb-2 h-8 w-8" />Chưa có lô được phân loại sang nhánh chế biến.</div>}</div>;
}
function Label({ text, children }: { text: string; children: React.ReactNode }) { return <label className="space-y-1 text-sm font-bold text-slate-700"><span>{text}</span>{children}</label>; }
function Input({ name, label, text = false, defaultValue }: { name: string; label: string; text?: boolean; defaultValue?: string }) { return <Label text={label}><input required name={name} type={text ? "text" : "number"} min={text ? undefined : "0.01"} step={text ? undefined : "0.01"} defaultValue={defaultValue} className="h-11 w-full rounded-xl border px-3 font-normal" /></Label>; }
