-- AlterEnum
ALTER TYPE "ProcessingBatchStatus" ADD VALUE IF NOT EXISTS 'WAITING_FINISHED_QC';

-- AlterEnum
ALTER TYPE "FinishedProductLotStatus" ADD VALUE IF NOT EXISTS 'PENDING_QC';
ALTER TYPE "FinishedProductLotStatus" ADD VALUE IF NOT EXISTS 'WAITING_WAREHOUSE_IN';
ALTER TYPE "FinishedProductLotStatus" ADD VALUE IF NOT EXISTS 'QC_FAILED';
