"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useToast } from "@/components/ui/toast";

type Manager = { id: string; fullName: string | null; phone: string };
type Region = { id: string; code: string; name: string; province: string; district: string | null; ward: string | null; areaSize: number | null; status: string; _count: { farms: number }; managerAssignments: { areaManager: Manager }[] };
const labels: Record<string, string> = { DRAFT: "Nháp", PENDING: "Chờ duyệt", ACTIVE: "Hoạt động", SUSPENDED: "Tạm dừng", EXPIRED: "Hết hiệu lực", REVOKED: "Thu hồi" };

export function GrowingRegionsManager({ regions, managers }: { regions: Region[]; managers: Manager[] }) {
    const router = useRouter(); const { toast } = useToast(); const [busy, setBusy] = useState(false);
    async function call(url: string, method: string, body: unknown) { setBusy(true); try { const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message); toast({ title: payload.message, variant: "success" }); router.refresh(); } catch (error) { toast({ title: "Không thể cập nhật", description: error instanceof Error ? error.message : "Vui lòng thử lại.", variant: "destructive" }); } finally { setBusy(false); } }
    async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); await call("/api/admin/growing-regions", "POST", { code: f.get("code"), name: f.get("name"), province: f.get("province"), district: f.get("district"), ward: f.get("ward"), cropType: "Sầu riêng", cropVarieties: String(f.get("varieties") || "").split(",").map(x => x.trim()).filter(Boolean), exportMarkets: [] }); }
    return <div className="space-y-5"><form onSubmit={create} className="grid gap-3 rounded-3xl border bg-white p-5 shadow-sm sm:grid-cols-2 lg:grid-cols-6"><Input name="code" required placeholder="Mã vùng" /><Input name="name" required placeholder="Tên vùng" /><Input name="province" required placeholder="Tỉnh/thành" /><Input name="district" placeholder="Huyện" /><Input name="ward" placeholder="Xã" /><Input name="varieties" placeholder="Giống, cách nhau dấu phẩy" /><Button disabled={busy} className="sm:col-span-2 lg:col-span-6">Tạo vùng trồng</Button></form><div className="grid gap-4 lg:grid-cols-2">{regions.map(region => <article key={region.id} className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-brand-700">{region.code}</p><h2 className="text-lg font-black">{region.name}</h2><p className="text-sm text-slate-500">{[region.ward, region.district, region.province].filter(Boolean).join(", ")}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{labels[region.status] || region.status}</span></div><p className="mt-3 text-sm">{region._count.farms} vườn · Trưởng ban: <b>{region.managerAssignments[0]?.areaManager.fullName || "Chưa phân công"}</b></p><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_auto]"><select id={`manager-${region.id}`} defaultValue={region.managerAssignments[0]?.areaManager.id || ""} className="h-10 rounded-xl border bg-white px-3 text-sm"><option value="">Chọn Trưởng ban</option>{managers.map(manager => <option key={manager.id} value={manager.id}>{manager.fullName || manager.phone}</option>)}</select><Button type="button" size="sm" disabled={busy} onClick={() => { const element = document.getElementById(`manager-${region.id}`) as HTMLSelectElement; if (element.value) void call("/api/admin/region-assignments", "POST", { areaManagerId: element.value, growingRegionId: region.id }); }}>Phân công</Button></div><div className="mt-3 flex flex-wrap gap-2">{region.status !== "ACTIVE" && <Button size="sm" onClick={() => void call("/api/admin/growing-regions", "PATCH", { id: region.id, status: "ACTIVE", reason: "Admin kích hoạt vùng" })}>Kích hoạt</Button>}{region.status === "ACTIVE" && <Button size="sm" variant="outline" onClick={() => void call("/api/admin/growing-regions", "PATCH", { id: region.id, status: "SUSPENDED", reason: "Admin tạm dừng vùng" })}>Tạm dừng</Button>}</div></article>)}</div></div>;
}
