import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/store-marketplace";
async function farmer() { return requireRole(["FARMER"]); }
export async function GET() { const s = await farmer(); if (!s) return NextResponse.json({ success: false }, { status: 403 }); return NextResponse.json({ success: true, data: await prisma.cartItem.findMany({ where: { userId: s.user.id }, include: { product: { include: { store: { select: { id: true, name: true, status: true } } } } }, orderBy: { createdAt: "desc" } }) }); }
export async function POST(request: Request) { const s = await farmer(); if (!s) return NextResponse.json({ success: false }, { status: 403 }); const p = z.object({ productId: z.string(), quantity: z.number().int().min(1).max(999).default(1) }).safeParse(await request.json()); if (!p.success) return NextResponse.json({ success: false }, { status: 400 }); const product = await prisma.storeProduct.findFirst({ where: { id: p.data.productId, status: "APPROVED", deletedAt: null, store: { status: "APPROVED" } } }); if (!product || product.stock < p.data.quantity) return NextResponse.json({ success: false, message: "Sản phẩm không khả dụng hoặc không đủ tồn kho." }, { status: 400 }); const data = await prisma.cartItem.upsert({ where: { userId_productId: { userId: s.user.id, productId: product.id } }, create: { userId: s.user.id, productId: product.id, quantity: p.data.quantity }, update: { quantity: { increment: p.data.quantity } } }); return NextResponse.json({ success: true, data }); }
export async function PATCH(request: Request) { const s = await farmer(); if (!s) return NextResponse.json({ success: false }, { status: 403 }); const p = z.object({ id: z.string(), quantity: z.number().int().min(1).max(999) }).safeParse(await request.json()); if (!p.success) return NextResponse.json({ success: false }, { status: 400 }); const item = await prisma.cartItem.findFirst({ where: { id: p.data.id, userId: s.user.id }, include: { product: true } }); if (!item || item.product.stock < p.data.quantity) return NextResponse.json({ success: false, message: "Số lượng vượt tồn kho." }, { status: 400 }); return NextResponse.json({ success: true, data: await prisma.cartItem.update({ where: { id: item.id }, data: { quantity: p.data.quantity } }) }); }
export async function DELETE(request: Request) { const s = await farmer(); if (!s) return NextResponse.json({ success: false }, { status: 403 }); const id = new URL(request.url).searchParams.get("id"); if (!id) return NextResponse.json({ success: false }, { status: 400 }); await prisma.cartItem.deleteMany({ where: { id, userId: s.user.id } }); return NextResponse.json({ success: true }); }
