"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { CalendarPlus, LockKeyhole, Sprout, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/components/ui/toast";
import { formatVietnameseDate } from "@/lib/date-format";

const stages = [["POST_HARVEST_RECOVERY", "Phục hồi sau thu hoạch"], ["MAKING_SPROUT", "Làm đọt"], ["FLOWER_INDUCTION", "Xử lý ra hoa"], ["FLOWERING", "Ra hoa"], ["FRUIT_SETTING", "Đậu trái"], ["FRUIT_GROWING", "Nuôi trái"], ["PRE_HARVEST", "Trước thu hoạch"], ["HARVEST", "Thu hoạch"]] as const;
type Props = { farmId: string; farmName: string; activeSeasonId?: string; activeSeasonName?: string; currentStage?: string; startedAt?: string; newLogHref: string };

export function CropSeasonActions({ farmId, farmName, activeSeasonId, activeSeasonName, currentStage, startedAt, newLogHref }: Props) {
    const router = useRouter(); const { toast } = useToast(); const [busy, setBusy] = useState(false); const [open, setOpen] = useState(false);
    async function request(body: Record<string, unknown>) { const response = await fetch("/api/crop-seasons", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || "Không thể cập nhật vụ mùa."); toast({ title: payload.message, variant: "success" }); router.refresh(); }
    async function closeSeason() { setBusy(true); try { await request({ action: "CLOSE", seasonId: activeSeasonId }); } catch (error) { toast({ title: "Không thể đóng vụ mùa", description: error instanceof Error ? error.message : "Vui lòng thử lại.", variant: "destructive" }); } finally { setBusy(false); } }
    async function createSeason(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { await request({ action: "CREATE", farmId, targetYear: Number(form.get("targetYear")), startedAt: form.get("startedAt"), startingStage: form.get("startingStage"), notes: form.get("notes") }); setOpen(false); } catch (error) { toast({ title: "Không thể bắt đầu vụ mùa", description: error instanceof Error ? error.message : "Vui lòng thử lại.", variant: "destructive" }); } finally { setBusy(false); } }
    const stageLabel = stages.find(([value]) => value === currentStage)?.[1] ?? currentStage ?? "Phục hồi sau thu hoạch";
    return <>
        {activeSeasonId ? <section className="rounded-3xl border border-brand-100 bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-brand-700">{farmName}</p><div className="mt-1 flex flex-wrap items-center gap-2"><h2 className="text-xl font-black text-slate-900">{activeSeasonName}</h2><span className="inline-flex items-center gap-1 rounded-full bg-brand-50 px-3 py-1 text-xs font-bold text-brand-700"><span className="h-2 w-2 rounded-full bg-brand-500" />Đang canh tác</span></div><p className="mt-2 text-sm text-slate-600">Giai đoạn hiện tại: <b className="text-slate-900">{stageLabel}</b>{startedAt ? ` · Bắt đầu ${formatVietnameseDate(startedAt)}` : ""}</p></div><div className="flex flex-wrap gap-2"><Button asChild><Link href={newLogHref}>Ghi nhật ký</Link></Button><Button type="button" variant="outline" disabled={busy} onClick={() => void closeSeason()}><LockKeyhole className="mr-2 h-4 w-4" />Đóng vụ</Button></div></div></section>
        : <section className="rounded-3xl border border-dashed border-brand-300 bg-brand-50 p-5"><Sprout className="h-7 w-7 text-brand-700" /><h2 className="mt-3 text-lg font-black text-slate-900">{farmName}</h2><p className="mt-1 text-sm text-slate-600">Chưa có vụ mùa đang hoạt động.</p><Button type="button" className="mt-4" onClick={() => setOpen(true)}><CalendarPlus className="mr-2 h-4 w-4" />Bắt đầu vụ mùa mới</Button></section>}
        {open && <div className="fixed inset-0 z-[150] flex h-full min-h-screen w-screen items-center justify-center overflow-y-auto bg-slate-950/60 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><form onSubmit={createSeason} className="my-auto w-full max-w-lg rounded-3xl bg-white p-5 shadow-2xl sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-black text-slate-900">Bắt đầu vụ mùa mới</h2><p className="mt-1 text-sm text-slate-500">Năm vụ là năm thu hoạch mục tiêu.</p></div><button type="button" onClick={() => setOpen(false)} className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100" aria-label="Đóng"><X className="h-5 w-5" /></button></div><div className="mt-5 space-y-4"><div><label className="text-sm font-bold text-slate-700">Vườn</label><Input value={farmName} disabled className="mt-1" /></div><div className="grid gap-4 sm:grid-cols-2"><div><label htmlFor="season-year" className="text-sm font-bold text-slate-700">Vụ mùa</label><Input id="season-year" name="targetYear" type="number" min={new Date().getFullYear()} max={2100} defaultValue={new Date().getFullYear() + 1} required className="mt-1" /></div><div><label htmlFor="season-start" className="text-sm font-bold text-slate-700">Ngày bắt đầu</label><Input id="season-start" name="startedAt" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required className="mt-1" /></div></div><div><label htmlFor="season-stage" className="text-sm font-bold text-slate-700">Giai đoạn bắt đầu</label><select id="season-stage" name="startingStage" defaultValue="POST_HARVEST_RECOVERY" className="mt-1 h-11 w-full rounded-2xl border border-slate-200 bg-white px-4 text-sm">{stages.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div><label htmlFor="season-notes" className="text-sm font-bold text-slate-700">Ghi chú <span className="font-normal text-slate-400">(không bắt buộc)</span></label><Textarea id="season-notes" name="notes" maxLength={500} className="mt-1 min-h-20" /></div></div><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setOpen(false)}>Hủy</Button><Button type="submit" disabled={busy}>{busy ? "Đang tạo..." : "Bắt đầu vụ mùa"}</Button></div></form></div>}
    </>;
}
