"use client";
import { useMemo, useState } from "react";
import { CalendarDays, MapPin, Scale, Sprout } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type HarvestRow = { id: string; code: string; status: string; expectedWeight: string | number; weightUnit: string; expectedHarvestDate: string; expectedPricePerKg?: string | number | null; transactionNote?: string | null; farm: { farmName: string; farmCode?: string; address: string; durianVariety: string }; farmer?: { fullName: string; phone: string } };
const statusLabels:Record<string,string>={WAITING_CONFIRMATION:"Chờ xác nhận",CONFIRMED:"Đã xác nhận",REJECTED:"Đã từ chối",HARVESTING:"Đang thu hoạch",HARVESTED:"Đã thu hoạch",DELIVERY_CONFIRMED:"Đã giao nhận",COMPLETED:"Hoàn tất",CANCELLED:"Đã hủy"};
const tabs=[{value:"all",label:"Tất cả"},{value:"WAITING_CONFIRMATION",label:"Mới / Chờ xác nhận"},{value:"CONFIRMED",label:"Đã xác nhận"},{value:"upcoming",label:"Sắp thu hoạch"},{value:"HARVESTED",label:"Đã thu hoạch"},{value:"REJECTED",label:"Đã từ chối"}];
export function PartnerHarvests({initial}:{initial:HarvestRow[]}){
 const [rows,setRows]=useState(initial);const [tab,setTab]=useState("all");const [busy,setBusy]=useState<string|null>(null);
 const filtered=useMemo(()=>rows.filter(row=>tab==="all"?true:tab==="upcoming"?["CONFIRMED","HARVESTING"].includes(row.status):row.status===tab),[rows,tab]);
 async function act(id:string,action:string){const reason=action==="REJECT"?prompt("Lý do từ chối")||"":undefined;const receivedWeight=action==="RECEIVE"?Number(prompt("Khối lượng thực nhận (kg)")||0):undefined;if(action==="REJECT"&&!reason)return;if(action==="RECEIVE"&&!receivedWeight)return;setBusy(id);try{const response=await fetch(`/api/harvests/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,reason,receivedWeight})});if(response.ok){const result=await response.json();setRows(current=>current.map(item=>item.id===id?{...item,status:result.data.status}:item));}}finally{setBusy(null);}}
 return <section className="space-y-5"><div className="flex gap-2 overflow-x-auto pb-1">{tabs.map(item=><button key={item.value} onClick={()=>setTab(item.value)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-bold ${tab===item.value?"bg-brand-600 text-white":"bg-slate-100 text-slate-600"}`}>{item.label}</button>)}</div><div className="grid gap-4 lg:grid-cols-2">{filtered.map(item=><Card key={item.id} className="overflow-hidden"><CardHeader className="border-b bg-slate-50"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-brand-600">{item.code}</p><CardTitle className="mt-1">{item.farm.farmName}</CardTitle></div><span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-slate-600 shadow-sm">{statusLabels[item.status]??item.status}</span></div></CardHeader><CardContent className="space-y-4 pt-5"><div className="grid grid-cols-2 gap-3 text-sm"><p className="flex gap-2"><Sprout className="h-4 w-4 text-brand-600"/><span><small className="text-slate-400">Giống</small><br/><b>{item.farm.durianVariety}</b></span></p><p className="flex gap-2"><Scale className="h-4 w-4 text-brand-600"/><span><small className="text-slate-400">Sản lượng dự kiến</small><br/><b>{Number(item.expectedWeight).toLocaleString("vi-VN")} {item.weightUnit}</b></span></p><p className="flex gap-2"><CalendarDays className="h-4 w-4 text-brand-600"/><span><small className="text-slate-400">Ngày dự kiến</small><br/><b>{new Date(item.expectedHarvestDate).toLocaleDateString("vi-VN")}</b></span></p><p className="flex gap-2"><MapPin className="h-4 w-4 text-brand-600"/><span><small className="text-slate-400">Khu vực</small><br/><b>{item.farm.address}</b></span></p></div>{item.expectedPricePerKg&&<p className="rounded-xl bg-brand-50 px-3 py-2 text-sm text-brand-800">Giá đề xuất: <b>{Number(item.expectedPricePerKg).toLocaleString("vi-VN")} đ/kg</b></p>}{item.status==="WAITING_CONFIRMATION"&&<div className="flex gap-2"><Button disabled={busy===item.id} onClick={()=>void act(item.id,"CONFIRM")}>Xác nhận thu mua</Button><Button disabled={busy===item.id} variant="outline" onClick={()=>void act(item.id,"REJECT")}>Từ chối</Button></div>}{["HARVESTED","DELIVERY_CONFIRMED"].includes(item.status)&&<Button disabled={busy===item.id} onClick={()=>void act(item.id,"RECEIVE")}>Xác nhận đã nhận hàng</Button>}</CardContent></Card>)}{!filtered.length&&<p className="rounded-3xl border border-dashed bg-white p-10 text-center text-slate-500 lg:col-span-2">Không có phiếu trong nhóm này.</p>}</div></section>;
}
