import assert from "node:assert/strict";
import { allocateFifo, groupMaterials, type FifoMovement } from "../src/lib/material-fifo";
import { isSupplyUsage } from "../src/lib/farmer-stock-ledger";

const movement = (id: string, type: string, quantity: number, unitPrice: number, day: string, supplyId = "tilt") : FifoMovement => ({ id, type, quantity, unitPrice, supplyId, actionDate: new Date(day + "T00:00:00Z"), createdAt: new Date(day + "T01:00:00Z") });
const receipts = [movement("sep01", "IN", 3, 180000, "2026-09-01"), movement("sep15", "IN", 10, 190000, "2026-09-15"), movement("sep25", "IN", 6, 200000, "2026-09-25")];
const output = movement("use", "OUT", 8, 999999, "2026-10-02");
const result = allocateFifo([...receipts, output]);
assert.deepEqual(result.exports.get("use")?.allocations.map(a => [a.transactionId, a.quantity]), [["sep01", 3], ["sep15", 5]]);
assert.equal(result.exports.get("use")?.totalAmount, 1490000);
assert.equal(result.balances.get("tilt"), 11);
assert.equal(allocateFifo([...receipts, { ...output, quantity: 5 }]).balances.get("tilt"), 14);
assert.equal(allocateFifo(receipts).balances.get("tilt"), 19);
assert.throws(() => allocateFifo([...receipts, { ...output, quantity: 20 }]), /vượt quá/);
assert.throws(() => allocateFifo([...receipts, { ...output, actionDate: new Date("2026-08-01") }]), /vượt quá/);
const later = movement("later", "OUT", 5, 0, "2026-10-03");
const revised = allocateFifo([...receipts, { ...output, quantity: 2 }, later]);
assert.deepEqual(revised.exports.get("later")?.allocations.map(a => [a.transactionId, a.quantity]), [["sep01", 1], ["sep15", 4]]);
assert.equal(revised.exports.get("later")?.totalAmount, 940000);
const multipleSupplies = allocateFifo([receipts[0], { ...receipts[1], supplyId: "second-record" }, output]);
assert.equal(multipleSupplies.balances.get("tilt"), 0);
assert.equal(multipleSupplies.balances.get("second-record"), 5);
assert.equal(multipleSupplies.exports.get("use")?.allocations[1].supplyId, "second-record");
const expiry = new Date("2027-10-10");
assert.equal(allocateFifo([{ ...receipts[0], expiryDate: expiry }, { ...output, quantity: 1 }]).exports.get("use")?.allocations[0].expiryDate, expiry.toISOString());
const grouped = groupMaterials([{ id: "a", name: "Tilt", type: "PESTICIDE", unit: "chai 250ml", quantity: 3 }, { id: "b", name: " tilt ", type: "PESTICIDE", unit: "chai 250ml", quantity: 10 }, { id: "c", name: "Tilt", type: "PESTICIDE", unit: "chai 1L", quantity: 6 }]);
assert.equal(grouped.length, 2);
assert.equal(grouped[0].quantity, 13);
assert.deepEqual(grouped[0].memberIds, ["a", "b"]);
assert.equal(groupMaterials([{ id: "small", name: "Tilt", type: "PESTICIDE", unit: "chai", packaging: "250ml", quantity: 3 }, { id: "large", name: "Tilt", type: "PESTICIDE", unit: "chai", packaging: "1L", quantity: 10 }]).length, 2);
assert.equal(isSupplyUsage({ type: "OUT", exportPurpose: "CULTIVATION", farmId: "farm", cropSeasonId: "season" }), true);
for (const exportPurpose of ["DISPOSAL", "OTHER"]) assert.equal(isSupplyUsage({ type: "OUT", exportPurpose, farmId: "farm", cropSeasonId: "season" }), false);
assert.equal(isSupplyUsage({ type: "OUT", exportPurpose: "CULTIVATION" }), false);
assert.equal(isSupplyUsage({ type: "OUT", purpose: "Hủy vật tư", farmId: "farm", cropSeasonId: "season" }), false);
assert.equal(isSupplyUsage({ type: "IN", exportPurpose: "CULTIVATION", farmId: "farm", cropSeasonId: "season" }), false);
console.log("PASS: FIFO allocation, real costs, edits/deletes, stock limits, product grouping and cultivation-only expenses.");
