import Link from "next/link";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { AlertCircle, CalendarClock, PackageCheck, Scale, WalletCards } from "lucide-react";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { Button } from "@/components/ui/button";

export default async function Page() {
    const session = await getServerSession(authOptions); if (!session?.user?.id || !["COLLECTOR", "PROCESSING_FACILITY"].includes(session.user.role)) redirect("/login");
    if (session.user.role === "PROCESSING_FACILITY") redirect("/dashboard/processing");
    const [facility, rows] = await Promise.all([prisma.partnerFacility.findUnique({ where: { ownerId: session.user.id } }), prisma.harvestRecord.findMany({ where: { buyerUserId: session.user.id }, select: { id: true, status: true, expectedWeight: true, expectedHarvestDate: true, expectedPricePerKg: true }, orderBy: { expectedHarvestDate: "asc" } })]);
    const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Ho_Chi_Minh" }).format(new Date()); const todayRows = rows.filter(row => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Ho_Chi_Minh" }).format(row.expectedHarvestDate) === today); const pending = rows.filter(row => row.status === "WAITING_CONFIRMATION"); const active = rows.filter(row => !["COMPLETED", "REJECTED", "CANCELLED"].includes(row.status)); const weight = todayRows.reduce((sum, row) => sum + Number(row.expectedWeight), 0); const payable = rows.filter(row => row.status === "COMPLETED").reduce((sum, row) => sum + Number(row.expectedWeight) * Number(row.expectedPricePerKg ?? 0), 0);
    const cards = [{ label: "Phiếu chờ xác nhận", value: pending.length, icon: AlertCircle }, { label: "Lịch thu mua hôm nay", value: todayRows.length, icon: CalendarClock }, { label: "Sản lượng dự kiến hôm nay", value: `${new Intl.NumberFormat("vi-VN").format(weight)} kg`, icon: Scale }, { label: "Đơn đang xử lý", value: active.length, icon: PackageCheck }, { label: "Giá trị thu mua đã hoàn tất", value: `${new Intl.NumberFormat("vi-VN").format(payable)} đ`, icon: WalletCards }];
    return <main className="mx-auto max-w-7xl space-y-6 px-4 py-7 sm:px-6"><header className="rounded-3xl bg-gradient-to-br from-orange-700 to-amber-500 p-6 text-white shadow-lg"><p className="text-sm font-bold text-orange-100">{facility?.name ?? "Vựa / Đơn vị thu mua"}</p><h1 className="mt-2 text-3xl font-black">Tổng quan thu mua</h1><p className="mt-2 text-orange-50">Theo dõi nguồn hàng và các việc cần xử lý hôm nay.</p></header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(({ label, value, icon: Icon }) => <article key={label} className="rounded-3xl border bg-white p-5 shadow-sm"><Icon className="h-6 w-6 text-orange-600" /><p className="mt-4 text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-slate-900">{value}</p></article>)}</section><section className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Công việc cần xử lý</h2><p className="mt-1 text-sm text-slate-500">Ưu tiên các phiếu nhà vườn đang chờ phản hồi.</p></div><Button asChild><Link href="/dashboard/partner/harvests">Xem phiếu thu hoạch</Link></Button></div>{pending.length === 0 ? <p className="mt-6 rounded-2xl bg-emerald-50 p-5 text-emerald-700">Hiện không có phiếu nào chờ xác nhận.</p> : <p className="mt-6 rounded-2xl bg-amber-50 p-5 font-semibold text-amber-800">Bạn có {pending.length} phiếu thu hoạch cần xác nhận.</p>}</section></main>;
}
