"use client";
import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { CalendarDays, ChevronLeft, ChevronRight } from "lucide-react";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

type Props={value?:string;defaultValue?:string;onChange?:(value:string)=>void;name?:string;id?:string;required?:boolean;min?:string;max?:string;className?:string;placeholder?:string;"aria-label"?:string};
const display=(iso:string)=>{const [y,m,d]=iso.split("-");return y&&m&&d?`${d}/${m}/${y}`:"";};
const parse=(text:string)=>{const match=text.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(!match)return null;const [,d,m,y]=match;const date=new Date(+y,+m-1,+d);return date.getFullYear()===+y&&date.getMonth()===+m-1&&date.getDate()===+d?`${y}-${m}-${d}`:null;};
const localToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;};
export function VietnameseDatePicker({value,defaultValue="",onChange,name,id,required,min="0000-00-00",max="9999-12-31",className,placeholder="dd/MM/yyyy",...rest}:Props){
 const controlled=value!==undefined;const [internal,setInternal]=useState(defaultValue);const iso=controlled?value:internal;const [text,setText]=useState(display(iso));const [open,setOpen]=useState(false);const [view,setView]=useState(()=>iso?new Date(`${iso}T00:00:00`):new Date());const anchor=useRef<HTMLDivElement|null>(null);
 useEffect(()=>setText(display(iso)),[iso]);function commit(next:string){if(min&&next<min)return;if(max&&next>max)return;if(!controlled)setInternal(next);onChange?.(next);}function type(textValue:string){const digits=textValue.replace(/\D/g,"").slice(0,8);const next=[digits.slice(0,2),digits.slice(2,4),digits.slice(4)].filter(Boolean).join("/");setText(next);const parsed=parse(next);if(parsed)commit(parsed);}function choose(day:number){const next=`${view.getFullYear()}-${String(view.getMonth()+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`;commit(next);setOpen(false);}
 const first=new Date(view.getFullYear(),view.getMonth(),1);const offset=(first.getDay()+6)%7;const total=new Date(view.getFullYear(),view.getMonth()+1,0).getDate();const cells=Array.from({length:offset+total},(_,i)=>i<offset?null:i-offset+1);const rect=anchor.current?.getBoundingClientRect();
 // @ts-expect-error Date bounds are normalized to non-empty defaults above.
 return <div ref={anchor} className={cn("relative",className)}><input type="hidden" name={name} value={iso} required={required}/><Input id={id} inputMode="numeric" maxLength={10} placeholder={placeholder} value={text} onChange={e=>type(e.target.value)} onBlur={()=>setText(display(iso))} aria-label={rest["aria-label"]}/><button type="button" className="absolute right-2 top-1/2 -translate-y-1/2 rounded-lg p-2 text-emerald-700 hover:bg-emerald-50" onClick={()=>{setView(iso?new Date(`${iso}T00:00:00`):new Date());setOpen(v=>!v);}} aria-label="Mở lịch chọn ngày"><CalendarDays className="h-4 w-4"/></button>{open&&rect&&typeof document!=="undefined"&&createPortal(<><button type="button" className="fixed inset-0 z-[209] cursor-default" onClick={()=>setOpen(false)} aria-label="Đóng lịch"/><div className="fixed z-[210] w-72 rounded-2xl border bg-white p-4 shadow-2xl" style={{left:Math.max(8,Math.min(rect.left,window.innerWidth-304)),top:Math.max(8,Math.min(rect.bottom+8,window.innerHeight-360))}}><div className="flex items-center justify-between"><button type="button" className="rounded-lg p-2 hover:bg-slate-100" onClick={()=>setView(new Date(view.getFullYear(),view.getMonth()-1,1))}><ChevronLeft className="h-4 w-4"/></button><b className="capitalize">{view.toLocaleDateString("vi-VN",{month:"long",year:"numeric"})}</b><button type="button" className="rounded-lg p-2 hover:bg-slate-100" onClick={()=>setView(new Date(view.getFullYear(),view.getMonth()+1,1))}><ChevronRight className="h-4 w-4"/></button></div><div className="mt-3 grid grid-cols-7 text-center text-xs font-bold text-slate-400">{["T2","T3","T4","T5","T6","T7","CN"].map(d=><span key={d} className="py-2">{d}</span>)}</div><div className="grid grid-cols-7">{cells.map((day,index)=>day?<button type="button" key={day} disabled={(min&&`${view.getFullYear()}-${String(view.getMonth()+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`<min)||(max&&`${view.getFullYear()}-${String(view.getMonth()+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`>max)} onClick={()=>choose(day)} className={`m-0.5 grid h-8 w-8 place-items-center rounded-full text-sm hover:bg-emerald-100 disabled:text-slate-300 ${iso===`${view.getFullYear()}-${String(view.getMonth()+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`?"bg-emerald-600 font-bold text-white hover:bg-emerald-600":""}`}>{day}</button>:<span key={`e-${index}`}/>)}</div><button type="button" className="mt-3 w-full rounded-xl bg-emerald-50 py-2 text-sm font-bold text-emerald-700" onClick={()=>{const today=localToday();commit(today);setOpen(false);}}>Chọn hôm nay</button></div></>,document.body)}</div>;
}
